=== bbossgroups/bboss/bboss-persistent/resources-test/database_3_2.dtd
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<!--
    Torque XML database schema DTD
    $Id: database.dtd,v 1.8 2005/06/27 21:34:10 tfischer Exp $
-->

<!--
For: database.defaultIdMethod and table.idMethod

Do not use autoincrement or sequence. They are deprecated in favor of
using native which will use the Connection pool to determine
which database it is talking to (yes, it knows that) and then use
whatever native database methodology for insert increments that it can.
Otherwise, you should use idbroker or none. none is good if you have a
table that is just a join table. idbroker is good if you want a
centralized repository for brokering out clumps of id's in a database
agnostic way.
-->

<!--

defaultJavaNamingMethod determines how a table or column name,
from the name attribute in the xml database file, is converted to a
Java class or method name.

     nochange   - indicates not change is performed.
     underscore - Underscores and dots are removed, first letter is
              capitalized, first letter after an underscore
              is capitalized, first letter after a dot is capitalized,
              the rest of the letters are converted to lowercase.
     underscoreOmitSchema - The section of the name before and including
              the last dot in the name is removed. For the remaining part,
              underscores are removed, first letter is capitalized,
              first letter after an underscore is capitalized,
              the rest of the letters are converted to lowercase.
     javaname   - same as underscore, but no letters are converted
              to lowercase.
-->

<!ELEMENT database (external-schema*, domain*, table+)>
<!ATTLIST database
  name CDATA #REQUIRED
  defaultIdMethod (idbroker|native|none) "none"
  defaultJavaType (object|primitive) "primitive"
  package CDATA #IMPLIED
  baseClass CDATA #IMPLIED
  basePeer CDATA #IMPLIED
  defaultJavaNamingMethod (nochange|underscore|underscoreOmitSchema|javaname) "underscore"
  heavyIndexing (true|false) "false"
>

<!ELEMENT external-schema EMPTY>
<!ATTLIST external-schema
  filename CDATA #REQUIRED
>

<!ELEMENT domain EMPTY>
<!ATTLIST domain
  name CDATA #REQUIRED
  type
    (
          BIT  | TINYINT | SMALLINT    | INTEGER    | BIGINT    | FLOAT
        | REAL | NUMERIC | DECIMAL     | CHAR       | VARCHAR   | LONGVARCHAR
        | DATE | TIME    | TIMESTAMP   | BINARY     | VARBINARY | LONGVARBINARY
        | NULL | OTHER   | JAVA_OBJECT | DISTINCT   | STRUCT    | ARRAY
        | BLOB | CLOB    | REF         | BOOLEANINT | BOOLEANCHAR
        | DOUBLE
    ) "VARCHAR"
  size CDATA #IMPLIED
  scale CDATA #IMPLIED
  default CDATA #IMPLIED
  description CDATA #IMPLIED
>


<!--
     note: the interface="true", requires that useManagers=true in the
     properties file.
-->
<!ELEMENT table (column+,(foreign-key|index|unique|id-method-parameter)*)>
<!ATTLIST table
  name CDATA #REQUIRED
  javaName CDATA #IMPLIED
  idMethod (idbroker|native|none|null) "null"
  skipSql (true|false) "false"
  abstract (true|false) "false"
  baseClass CDATA #IMPLIED
  basePeer CDATA #IMPLIED
  alias CDATA #IMPLIED
  interface CDATA #IMPLIED
  javaNamingMethod (nochange|underscore|underscoreOmitSchema|javaname) #IMPLIED
  heavyIndexing (true|false) #IMPLIED
  description CDATA #IMPLIED
>

<!ELEMENT id-method-parameter EMPTY>
<!ATTLIST id-method-parameter
  name CDATA "default"
  value CDATA #REQUIRED
>

<!ELEMENT column (inheritance*)>
<!ATTLIST column
  name CDATA #REQUIRED
  javaName CDATA #IMPLIED
  primaryKey (true|false) "false"
  required (true|false) "false"
  protected (true|false) "false"
  domain CDATA #IMPLIED
  type
    (
          BIT  | TINYINT | SMALLINT    | INTEGER    | BIGINT    | FLOAT
        | REAL | NUMERIC | DECIMAL     | CHAR       | VARCHAR   | LONGVARCHAR
        | DATE | TIME    | TIMESTAMP   | BINARY     | VARBINARY | LONGVARBINARY
        | NULL | OTHER   | JAVA_OBJECT | DISTINCT   | STRUCT    | ARRAY
        | BLOB | CLOB    | REF         | BOOLEANINT | BOOLEANCHAR
        | DOUBLE
    ) #IMPLIED
  javaType (object|primitive) #IMPLIED
  size CDATA #IMPLIED
  scale CDATA #IMPLIED
  default CDATA #IMPLIED
  autoIncrement (true|false) #IMPLIED
  inheritance (single|false) "false"
  inputValidator CDATA #IMPLIED
  javaNamingMethod (nochange|underscore|javaname) #IMPLIED
  description CDATA #IMPLIED
>

<!ELEMENT inheritance EMPTY>
<!ATTLIST inheritance
  key CDATA #REQUIRED
  class CDATA #REQUIRED
  extends CDATA #IMPLIED
>

<!ELEMENT foreign-key (reference+)>
<!ATTLIST foreign-key
  foreignTable CDATA #REQUIRED
  name CDATA #IMPLIED
  onUpdate (cascade|setnull|restrict|none) "none"
  onDelete (cascade|setnull|restrict|none) "none"
>

<!ELEMENT reference EMPTY>
<!ATTLIST reference
  local CDATA #REQUIRED
  foreign CDATA #REQUIRED
>

<!ELEMENT index (index-column+)>
<!ATTLIST index
  name CDATA #IMPLIED
>

<!ELEMENT index-column EMPTY>
<!ATTLIST index-column
  name CDATA #REQUIRED
  size CDATA #IMPLIED
>

<!ELEMENT unique (unique-column+)>
<!ATTLIST unique
  name CDATA #IMPLIED
>

<!ELEMENT unique-column EMPTY>
<!ATTLIST unique-column
  name CDATA #REQUIRED
>

=== bbossgroups/bboss/bboss-persistent/src/com/frameworkset/orm/engine/model/tabletest-schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "database_3_2.dtd">

<database name="iddb" defaultIdMethod="idbroker">

  <table name="table_idbroker">
    <column name="table_a_id" required="true" primaryKey="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
  </table>
  
  <table name="table_native" idMethod="native">
    <column name="table_a_id" required="true" primaryKey="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
  </table>

  <table name="nopk">
    <column name="col_a" type="CHAR" size="5" />
    <column name="col_b" type="CHAR" size="5" />
  </table>

  <table name="singlepk">
    <column name="singlepk_id" required="true" primaryKey="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
  </table>

  <table name="multipk">
    <column name="multipk_a" required="true" primaryKey="true" type="INTEGER" />
    <column name="multipk_b" required="true" primaryKey="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
  </table>

  <table name="singlefk">
    <column name="id" required="true" primaryKey="true" type="INTEGER" />
    <column name="singlepk_id" required="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
    <foreign-key foreignTable="singlepk">
      <reference local="singlepk_id" foreign="singlepk_id"/>
    </foreign-key>
  </table>

  <table name="singlefk1">
    <column name="id" required="true" primaryKey="true" type="INTEGER" />
    <column name="singlepk_id" required="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
    <foreign-key foreignTable="singlefk" onUpdate="cascade" onDelete="setnull">
      <reference local="singlepk_id" foreign="id"/>
    </foreign-key>
  </table>
  
  <table name="multifk">
    <column name="id" required="true" primaryKey="true" type="INTEGER" />
    <column name="multipk_a" required="true" type="INTEGER" />
    <column name="multipk_b" required="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
    <foreign-key foreignTable="multipk">
      <reference local="multipk_a" foreign="multipk_a"/>
      <reference local="multipk_b" foreign="multipk_b"/>
    </foreign-key>
  </table>
  
  <table name="unique_test">
    <column name="id" required="true" primaryKey="true" type="INTEGER" />
    <column name="col_a" type="CHAR" size="5" />
    <column name="col_b" type="CHAR" size="5" />
    <unique name="unique_name">
      <unique-column name="col_a"/>
      <unique-column name="col_b"/>
    </unique>
  </table>
  
  
</database>

=== bbossgroups/bboss/bboss-persistent/src/com/frameworkset/orm/engine/model/domaintest-schema.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE database SYSTEM "resources/database_3_2.dtd">

<database name="domaindb" defaultIdMethod="idbroker">
  <domain name="amount" type="NUMERIC" size="10" scale="2" default="0" description="amount domain" />
  
  <table name="product">
    <column name="product_id" required="true" primaryKey="true" type="INTEGER" />
    <column name="name" size="40" />
    <column name="price" domain="amount" />
  </table>
  
  <table name="article">
    <column name="article_id" required="true" primaryKey="true" type="INTEGER" />
    <column name="name" size="40" />
    <column name="price" domain="amount" size="12" default="1000" />
    <column name="note" type="VARCHAR" size="50" default="default note" />
    <column name="decimal_col" type="DECIMAL" size="10" scale="3" />
    <column name="date_col" type="DATE"/>
  </table>

  <table name="native" idMethod="native">
    <column name="native_id" required="true" autoIncrement="true"
            primaryKey="true" type="INTEGER" />
    <column name="name" size="40" />
  </table>

  <table name="types" description="used to test the handling for all supported types">
    <column name="cbit" type="BIT" />
    <column name="ctinyint" type="TINYINT" />
    <column name="csmallint" type="SMALLINT" />
    <column name="cbigint" type="BIGINT" />
    <column name="cfloat" type="FLOAT" />
    <column name="creal" type="REAL" />
    <column name="cnumeric" type="NUMERIC" />
    <column name="cdecimal" type="DECIMAL" />
    <column name="cchar" type="CHAR" />
    <column name="cvarchar" type="VARCHAR" />
    <column name="clongvarchar" type="LONGVARCHAR" />
    <column name="cdate" type="DATE" />
    <column name="ctime" type="TIME" />
    <column name="cinteger" type="INTEGER" />
    <column name="ctimestamp" type="TIMESTAMP" />
    <column name="cbinary" type="BINARY" />
    <column name="cvarbinary" type="VARBINARY" />
    <column name="clongvarbinary" type="LONGVARBINARY" />
    <column name="cnull" type="NULL" />
    <column name="cother" type="OTHER" />
    <column name="cjavaobject" type="JAVA_OBJECT" />
    <column name="cdistinct" type="DISTINCT" />
    <column name="cstruct" type="STRUCT" />
    <column name="carray" type="ARRAY" />
    <column name="cblob" type="BLOB" />
    <column name="cclob" type="CLOB" />
    <column name="cref" type="REF" />
    <column name="cbooleanint" type="BOOLEANINT" />
    <column name="cbooleanchar" type="BOOLEANCHAR" />
    <column name="cdouble" type="DOUBLE" />
  </table>

</database>
